### ISSUE TITLE
Issue in documentation

### ISSUE THREAD

**Issue by Grimille** [wahyubucil/adonis-mix-asset#4]
## Description

The documentation says to install adonis-mix-asset as a dev-dependency although it is required in production. However laravel-mix can and should be installed in --save-dev mode.

## Package version

Tested on : "adonis-mix-asset": "^2.1.0", "laravel-mix": "^6.0.0-beta.17", AdonisJS v5

## Error Message & Stack Trace
```
Error: Cannot find module 'adonis-mix-asset'
Require stack:
- /Users/mickael/Documents/build/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at resolveFileName (/Users/mickael/Documents/build/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/Users/mickael/Documents/build/node_modules/resolve-from/index.js:43:9)
    at Object.module.exports [as default] (/Users/mickael/Documents/build/node_modules/resolve-from/index.js:46:47)
    at Object.resolveFrom (/Users/mickael/Documents/build/node_modules/@poppinss/utils/build/src/resolveFrom.js:25:34)
    at Registrar.loadProvider (/Users/mickael/Documents/build/node_modules/@adonisjs/fold/build/src/Registrar/index.js:49:23)
    at /Users/mickael/Documents/build/node_modules/@adonisjs/fold/build/src/Registrar/index.js:67:53
    at Array.forEach (<anonymous>)
    at Registrar.collect (/Users/mickael/Documents/build/node_modules/@adonisjs/fold/build/src/Registrar/index.js:66:23)
    at Registrar.register (/Users/mickael/Documents/build/node_modules/@adonisjs/fold/build/src/Registrar/index.js:96:14)
```

**Comment by wahyubucil** [comment]
I just realized it. Thanks!

I've several projects that already in production, and it just works. It's weird. It should have the same error too 😅

I'll update the readme right now
